runtime! archlinux.vim

set tabstop=4
set shiftwidth=4
set expandtab
set number
syntax on
set ignorecase
set smartcase
set clipboard+=unnamedplus
"I have 0 Idea why my backspace stopped working but this fixes it: Let's keep it for now"
set nocompatible
